name: Test Login Page

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' # Adjust based on your project

    - name: Install Dependencies
      run: dotnet restore

    - name: Build Solution
      run: dotnet build --configuration Release

    - name: Start WinAppDriver
      run: |
        curl -L -o WinAppDriver.msi https://github.com/microsoft/WinAppDriver/releases/download/v1.2.1/WinAppDriver.msi
        msiexec /i WinAppDriver.msi /quiet
        start /B WinAppDriver.exe

    - name: Run Tests
      run: dotnet test --logger "trx;LogFileName=test-results.trx"
